version: '3'
networks:
  mimi-net:
    driver: bridge
services:
  mimi-api:
    container_name: mimi-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ../mimi-api
    networks:
      - mimi-net
    ports:
      - 4000:4000
  mimi-web:
    container_name: mimi-web
    build:
      context: ../mimi-web
      args:
        API_URL: "https://mimi.shivalry.dev"
    stdin_open: true
    restart: unless-stopped
    ports:
      - "3000:3000"

    networks:
      - mimi-net
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mimi-net

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
